name: CI

on:
  push:
  pull_request:
    branches: [trunk]

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - run: make test