name: Docs

on:
  push:
    branches: [master, gha-docs] # TODO: Remove once done

jobs:
  docs:
    runs-on: ubuntu-20.04
    steps:
      - run: sudo apt-get update && sudo apt-get install texlive-binaries
      - uses: actions/checkout@v3
      - run: cd doc && ./gendocs.sh wacc
